version: '3'
services:
    web:
        build: .
        ports:
            - "80:8181"
        env_file: env-file.env
        depends_on:
            - postgres
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=supersecretpassword
            - POSTGRES_DB=azuredominion
