version: '3'
services:
    web:
        build: .
        ports:
            - "80:8181"
        environment:
            - BDR_USERNAME=postgres
            - BDR_HOST=postgres
            - BDR_PASSWORD=supersecretpassword
            - BDR_DATABASE=azuredominion
            - BDR_ELOBASEPATH=/elo
        depends_on:
            - postgres
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=supersecretpassword
            - POSTGRES_DB=azuredominion
